### ISSUE TITLE
Cannot modify User.companies

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#25]
I'm getting an error when I attempt to modify `User.companies` which contains a number of companies:

```
# Assuming there's already companies registered in stalker
companies = []
for client in Client.query.all():
    companies.append(client)

# Assuming there's already a user in stalker called Peter Griffin, with one or more companies already in the user.companies attribute:
for user in User.query.filter_by(name='Peter Griffin'):
    user.companies = companies

db.DBSession.commit() # <----- triggers the error
```

The error:

```
Traceback (most recent call last):
  File "C:\Users\IRUser\Desktop\stalker_manual_fixing.py", line 28, in <module>
    db.DBSession.commit()
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\session.py", line 776, in commit
    self.transaction.commit()
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\session.py", line 377, in commit
    self._prepare_impl()
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\session.py", line 357, in _prepare_impl
    self.session.flush()
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\session.py", line 1919, in flush
    self._flush(objects)
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\session.py", line 2001, in _flush
    flush_context.execute()
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\unitofwork.py", line 372, in execute
    rec.execute(self)
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\unitofwork.py", line 481, in execute
    self.dependency_processor.process_saves(uow, states)
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\dependency.py", line 558, in process_saves
    uowcommit, False)
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\dependency.py", line 575, in _synchronize
    sync.clear(dest, self.mapper, self.prop.synchronize_pairs)
  File "//192.168.0.225/Pipeline/bin/python/virtualenvs\python276_amd64_win7_skalman/Lib/site-packages\sqlalchemy\orm\sync.py", line 57, in clear
    (r, orm_util.state_str(dest))
AssertionError: Dependency rule tried to blank-out primary key column 'Client_Users.uid' on instance '<ClientUser at 0x564d320>'
```

**Comment by fredrikaverpil** [comment]
This issue should not be closed.

It is not possible to modify `User.companies`, as described in my previous comment.
