### ISSUE TITLE
pip install stalker - does not find required modules (sqlalchemy and jinja2)

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#28]
`pip install stalker` does not automatically download and install required modules.

```
(python2.7.9_win7-64_stalker0.2.13) Y:\bin\python\virtualenvs\python2.7.9_win7-6
4_stalker0.2.13\Scripts>pip install -U stalker
Collecting stalker
  Downloading stalker-0.2.13.tar.gz (519kB)
    100% |################################| 520kB 671kB/s
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\iruser\appdata\local\temp\pip-build-k2fqn4\stalker\setup.py
", line 5, in <module>
        import stalker
      File "stalker\__init__.py", line 41, in <module>
        from stalker.models.auth import Group, Permission, User, LocalSession, R
ole
      File "stalker\models\auth.py", line 27, in <module>
        from sqlalchemy import (Table, Column, Integer, ForeignKey, String, Date
Time,
    ImportError: No module named sqlalchemy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "c:\users\iruser\appdata\local\temp\pip-build-k2fqn4\stalker\setup.py
", line 5, in <module>

        import stalker

      File "stalker\__init__.py", line 41, in <module>

        from stalker.models.auth import Group, Permission, User, LocalSession, R
ole

      File "stalker\models\auth.py", line 27, in <module>

        from sqlalchemy import (Table, Column, Integer, ForeignKey, String, Date
Time,

    ImportError: No module named sqlalchemy

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in c:\users\irus
er\appdata\local\temp\pip-build-k2fqn4\stalker
```

**Comment by fredrikaverpil** [comment]
Workaround:
```
pip install sqlalchemy
pip install jinja2
pip install stalker
```

**Comment by fredrikaverpil** [comment]
This doesn't seem to be a problem with `0.2.15.1`. I'm closing this issue.
