### ISSUE TITLE
Query: latest Version object(s) from project

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#31]
Hi,

I need to create list of all of the `Version` objects in a certain project - but I'm only interested in the ones with the highest version number.

Today I do it like this:

```python
latest = []
tasks = Task.query.filter_by(project_id=1)
for task in tasks:
    for version in task.versions:
        latest.append(version.latest_version)
```

However, iterating over the versions in Python has proven to actually be a bit of a performance hit and I believe I would benefit greatly if I were able to instead perform the following kind of query (without having to iterate over `task.versions`):

```python
latest = Version.query.join(Task).filter(Task.project_id==1).filter(Version.max_version_number==Version.version_number).all()
```

[As far as I can tell](https://pythonhosted.org/stalker/generated/stalker.models.version.Version.html#stalker.models.version.Version), this kind of query is not possible, correct?

I get this error when attempting to run it:

```python
Traceback (most recent call last):
  File "\\192.168.0.226\pipeline\dev\skalman\skalman\uilib\browserfunctions.py", line 41, in <lambda>
    lambda: get_files_data(skalWin, proj_box))
  File "\\192.168.0.226\pipeline\dev\skalman\skalman\uilib\browserfunctions.py", line 354, in get_files_data
    progressbar=skalWin.progressbar)
  File "\\192.168.0.226\pipeline\dev\skalman\skalman\lib\stalkerscripts\stalkerquery.py", line 181, in versions_in_project
    ).filter(Version.max_version_number==Version.version_number
  File "c:\python27\lib\site-packages\sqlalchemy\orm\query.py", line 2588, in all
    return list(self)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "c:\python27\lib\site-packages\sqlalchemy\orm\query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "c:\python27\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "c:\python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "c:\python27\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'property' [SQL: 'SELECT "Versions".id AS "Versions_id", "Links".id AS "Links_id", "Entities".id AS "Entities_id", "SimpleEntities".stalker_version AS "SimpleEntities_stalker_version", "SimpleEntities".id AS "SimpleEntities_id", "SimpleEntities".entity_type AS "SimpleEntities_entity_type", "SimpleEntities".name AS "SimpleEntities_name", "SimpleEntities".description AS "SimpleEntities_description", "SimpleEntities".created_by_id AS "SimpleEntities_created_by_id", "SimpleEntities".updated_by_id AS "SimpleEntities_updated_by_id", "SimpleEntities".date_created AS "SimpleEntities_date_created", "SimpleEntities".date_updated AS "SimpleEntities_date_updated", "SimpleEntities".type_id AS "SimpleEntities_type_id", "SimpleEntities".generic_text AS "SimpleEntities_generic_text", "SimpleEntities".thumbnail_id AS "SimpleEntities_thumbnail_id", "SimpleEntities".html_style AS "SimpleEntities_html_style", "SimpleEntities".html_class AS "SimpleEntities_html_class", "Links".original_filename AS "Links_original_filename", "Links".full_path AS "Links_full_path", "Versions".task_id AS "Versions_task_id", "Versions".take_name AS "Versions_take_name", "Versions".version_number AS "Versions_version_number", "Versions".is_published AS "Versions_is_published", "Versions".created_with AS "Versions_created_with", "Versions".parent_id AS "Versions_parent_id" \nFROM "SimpleEntities" JOIN "Entities" ON "SimpleEntities".id = "Entities".id JOIN "Links" ON "Entities".id = "Links".id JOIN "Versions" ON "Links".id = "Versions".id JOIN ("SimpleEntities" AS "SimpleEntities_1" JOIN "Entities" AS "Entities_1" ON "SimpleEntities_1".id = "Entities_1".id JOIN "Tasks" AS "Tasks_1" ON "Entities_1".id = "Tasks_1".id) ON "Tasks_1".id = "Versions".task_id \nWHERE "Tasks_1".project_id = %(project_id_1)s AND "Versions".version_number = %(version_number_1)s'] [parameters: {'version_number_1': <property object at 0x00000000064186D8>, 'project_id_1': 1774}]
```

**Comment by fredrikaverpil** [comment]
This solved it for me:

```python
from stalker import db
from sqlalchemy.sql.expression import func
from sqlalchemy import tuple_

max_per_task = db.DBSession.query(
                    Version.task_id,
                    func.max(Version.version_number).label('max'))\
    .join(Task)\
    .filter(Task.project_id == proj_id)\
    .group_by(Version.task_id)\
    .subquery()

versions = Version.query\
    .join(max_per_task,
          tuple_(max_per_task.c.task_id, max_per_task.c.max) ==
          tuple_(Version.task_id, Version.version_number))\
    .all()
```

**Comment by eoyilmaz** [comment]
I'm glad that you have solved it. I'd have probably gone with a pure SQL when there are any speed concerns.

I've created a benchmark code that shows this:

```python
from stalker import db, Version, Task
from sqlalchemy.sql.expression import func
from sqlalchemy import tuple_
import time


proj_id = 23
config = {
    'sqlalchemy.url': 'postgresql://stalker_admin:stalker@localhost/stalker'
}
db.setup(config)


def measure_time(f):
    def inner_f():
        start = time.time()
        return_data = f()
        end = time.time()
        print ('%11s: %0.3f sec' % (f.__name__, (end - start)))
        return return_data

    return inner_f


@measure_time
def pure_python():
    max_per_task = db.DBSession.query(
        Version.task_id,
        func.max(Version.version_number).label('max'))\
        .join(Task)\
        .filter(Task.project_id == proj_id)\
        .group_by(Version.task_id)\
        .subquery()

    return Version.query\
        .join(max_per_task,
              tuple_(max_per_task.c.task_id, max_per_task.c.max) ==
              tuple_(Version.task_id, Version.version_number))\
        .all()


@measure_time
def simple_sql():
    sql = """
    select
        max("Versions".id) as id
    from "Versions"
        join "Tasks" on "Versions".task_id = "Tasks".id
        join "Projects" on "Tasks".project_id = "Projects".id
        where "Projects".id = %s
        group by "Versions".task_id, "Versions".take_name
    """ % proj_id

    conn = db.DBSession.connection()
    result = conn.execute(sql)
    return result.fetchall()


@measure_time
def complex_sql():
    sql = """
    select
        "Links".id as id,
        "Links".full_path as full_path
    from
        (select
            max("Versions".id) as id
        from "Versions"
        join "Tasks" on "Versions".task_id = "Tasks".id
        join "Projects" on "Tasks".project_id = "Projects".id
        where "Projects".id = %s
        group by "Versions".task_id, "Versions".take_name) as "sub_versions", "Links"
    where "Links".id = "sub_versions".id
    """ % proj_id

    conn = db.DBSession.connection()
    result = conn.execute(sql)
    return result.fetchall()


versions1 = pure_python()
versions2 = simple_sql()
versions3 = complex_sql()

# There should be a difference in versions count
# due to the "take_name" in sql queries
print "Versions1 count: %s" % len(versions1)
print "Versions2 count: %s" % len(versions2)
print "Versions3 count: %s" % len(versions3)
```
This outputs the following with our last movie project which had ~20k Tasks and ~160k Versions:
```python
pure_python: 3.284 sec
 simple_sql: 0.228 sec
complex_sql: 0.463 sec
Versions1 count: 16320
Versions2 count: 32780
Versions3 count: 32780
```
The difference in the version counts are due to the fact that the sql queries that I've written is also considering different ``take_name``s (which are versioned by their own version number sequence under the same Task).

**Comment by fredrikaverpil** [comment]
Ah, those are excellent comparisons. Thank you for putting that together. Yes, I agree the SQL queries look much nicer.

**Comment by fredrikaverpil** [comment]
Hi again,

I'm using your "simple_sql" example above and the `result.fetchall()` output can look like this:

```python
>>> print(result.fetchall())
[(1321,), (10816,), (20557,), (20545,), (20579,), (20549,), (20560,), (20573,), (20562,), (20591,), (20533,), (20585,), (20586,), (20506,), (20188,), (20537,), (20535,), (20547,), (20536,), (20577,), (20529,), (20588,), (20580,), (452,), (16809,), (14029,), (152,), (154,), (14032,), (20571,), (20575,), (20539,), (704,), (20540,), (20543,), (1325,), (18001,), (20542,), (20555,), (16544,), (20570,), (20532,), (20554,), (20534,), (20584,), (1331,), (20548,), (10814,), (16824,), (20564,), (20559,), (20538,), (20582,), (20530,), (20566,), (20587,), (454,)]
```

In order to get a list of `Version` objects, I'm now querying once per id:

```python
versions = []
for tpl in sql_result.fetchall():
    for item in tpl:
        version = Version.query.filter_by(id=item).first()
        versions.append(version)
```

Is it possible to perform a `Version.query` using a list of ids instead of just one id?

**Comment by eoyilmaz** [comment]
Yes you can use the **in_** filter operator:

```python
result = sql_result.fetchall()
latest_versions = Version.query.filter((Version.id.in_(result)).all()
```

**Comment by fredrikaverpil** [comment]
Aha, that's excellent!

Would [this](http://docs.sqlalchemy.org/en/latest/orm/internals.html#sqlalchemy.orm.properties.ColumnProperty.Comparator.in_) be the proper documentation for such operators?

**Comment by fredrikaverpil** [comment]
Hm, I initally thought it worked... but I see now I get this:

```python
AttributeError: Neither 'BinaryExpression' object nor 'Comparator' object has an attribute 'all'
```

I have this:

```python
    sql = """
    select
        max("Versions".id) as id
    from "Versions"
        join "Tasks" on "Versions".task_id = "Tasks".id
        join "Projects" on "Tasks".project_id = "Projects".id
        where "Projects".id = %s
        group by "Versions".task_id, "Versions".take_name
    """ % proj_id
    sql_result = db.DBSession.execute(sql)
    sql_result_list = sql_result.fetchall()
    versions = Version.query.filter((Version.id.in_(sql_result_list)).all())
```

**Comment by eoyilmaz** [comment]
Sorry, I though I've answered through the email, but it seems that it didn't end up here.

So what was wrong with your code is the extra parentheses (due to my fault in my previous post I believe), your code should look like:

```python
versions = Version.query.filter(Version.id.in_(sql_result_list)).all()
```

**Comment by fredrikaverpil** [comment]
Hm, I'm not having much luck with that, unfortunately. I'm using [pg8000](https://pypi.python.org/pypi/pg8000) but I switched to psycopg2 (because I know you use that) but I still get the very same error:

```python
Traceback (most recent call last):
  File "c:\users\iruser\code\repos\skalman\skalman\uilib\browser\browsersetup.py", line 65, in <lambda>
    lambda: setupfiles.get_files_data(skalWin, proj_box))
  File "c:\users\iruser\code\repos\skalman\skalman\uilib\browser\setupfiles.py", line 115, in get_files_data
    progressbar=skalWin.progressbar)
  File "c:\users\iruser\code\repos\skalman\skalman\lib\stalkerscripts\stalkerquery.py", line 237, in versions_in_project_fast
    versions = Version.query.filter(Version.id.in_(sql_result_list)).all()
  File "c:\python35\lib\site-packages\sqlalchemy\orm\query.py", line 2613, in all
    return list(self)
  File "c:\python35\lib\site-packages\sqlalchemy\orm\query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "c:\python35\lib\site-packages\sqlalchemy\orm\query.py", line 2776, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "c:\python35\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "c:\python35\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\python35\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "c:\python35\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "c:\python35\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "c:\python35\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\python35\lib\site-packages\sqlalchemy\util\compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "c:\python35\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "c:\python35\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'RowProxy' [SQL: 'SELECT "Versions".id AS "Versions_id", "Links".id AS "Links_id", "Entities".id AS "Entities_id", "SimpleEntities".stalker_version AS "SimpleEntities_stalker_version", "SimpleEntities".id AS "SimpleEntities_id", "SimpleEntities".entity_type AS "SimpleEntities_entity_type", "SimpleEntities".name AS "SimpleEntities_name", "SimpleEntities".description AS "SimpleEntities_description", "SimpleEntities".created_by_id AS "SimpleEntities_created_by_id", "SimpleEntities".updated_by_id AS "SimpleEntities_updated_by_id", "SimpleEntities".date_created AS "SimpleEntities_date_created", "SimpleEntities".date_updated AS "SimpleEntities_date_updated", "SimpleEntities".type_id AS "SimpleEntities_type_id", "SimpleEntities".generic_text AS "SimpleEntities_generic_text", "SimpleEntities".thumbnail_id AS "SimpleEntities_thumbnail_id", "SimpleEntities".html_style AS "SimpleEntities_html_style", "SimpleEntities".html_class AS "SimpleEntities_html_class", "Links".original_filename AS "Links_original_filename", "Links".full_path AS "Links_full_path", "Versions".task_id AS "Versions_task_id", "Versions".take_name AS "Versions_take_name", "Versions".version_number AS "Versions_version_number", "Versions".is_published AS "Versions_is_published", "Versions".created_with AS "Versions_created_with", "Versions".parent_id AS "Versions_parent_id" \nFROM "SimpleEntities" JOIN "Entities" ON "SimpleEntities".id = "Entities".id JOIN "Links" ON "Entities".id = "Links".id JOIN "Versions" ON "Links".id = "Versions".id \nWHERE "SimpleEntities".id IN (%(id_1)s, %(id_2)s, %(id_3)s, %(id_4)s, %(id_5)s, %(id_6)s, %(id_7)s, %(id_8)s, %(id_9)s, %(id_10)s, %(id_11)s, %(id_12)s, %(id_13)s, %(id_14)s, %(id_15)s, %(id_16)s, %(id_17)s, %(id_18)s, %(id_19)s, %(id_20)s, %(id_21)s, %(id_22)s, %(id_23)s, %(id_24)s, %(id_25)s, %(id_26)s, %(id_27)s, %(id_28)s, %(id_29)s, %(id_30)s, %(id_31)s, %(id_32)s, %(id_33)s, %(id_34)s, %(id_35)s, %(id_36)s, %(id_37)s, %(id_38)s, %(id_39)s, %(id_40)s, %(id_41)s, %(id_42)s, %(id_43)s, %(id_44)s, %(id_45)s, %(id_46)s, %(id_47)s, %(id_48)s, %(id_49)s, %(id_50)s, %(id_51)s, %(id_52)s, %(id_53)s, %(id_54)s, %(id_55)s, %(id_56)s, %(id_57)s)'] [parameters: {'id_2': (10816,), 'id_49': (16824,), 'id_4': (20545,), 'id_16': (20537,), 'id_56': (20587,), 'id_7': (20560,), 'id_52': (20538,), 'id_42': (20532,), 'id_46': (1331,), 'id_23': (20580,), 'id_28': (154,), 'id_29': (14032,), 'id_17': (20535,), 'id_38': (20542,), 'id_13': (20586,), 'id_8': (20573,), 'id_54': (20530,), 'id_20': (20577,), 'id_19': (20536,), 'id_27': (152,), 'id_53': (20582,), 'id_24': (452,), 'id_39': (20555,), 'id_12': (20585,), 'id_32': (20539,), 'id_11': (20533,), 'id_30': (20571,), 'id_21': (20529,), 'id_55': (20566,), 'id_5': (20579,), 'id_18': (20547,), 'id_41': (20570,), 'id_44': (20534,), 'id_26': (14029,), 'id_25': (16809,), 'id_57': (454,), 'id_34': (20540,), 'id_45': (20584,), 'id_47': (20548,), 'id_31': (20575,), 'id_37': (18001,), 'id_51': (20559,), 'id_14': (20506,), 'id_22': (20592,), 'id_9': (20562,), 'id_50': (20564,), 'id_36': (1325,), 'id_1': (1321,), 'id_35': (20543,), 'id_48': (10814,), 'id_3': (20557,), 'id_40': (16544,), 'id_43': (20554,), 'id_6': (20549,), 'id_15': (20188,), 'id_10': (20591,), 'id_33': (704,)}]
```

**Comment by fredrikaverpil** [comment]
I think the error above has something to do with that the SQL response is not a list but a list of tuples.

If you iterate over the SQL response and create a list out of the ids in the tuples it all works fine:

```python
def get_versions(proj_id):
    sql = """
    select
        max("Versions".id) as id
    from "Versions"
        join "Tasks" on "Versions".task_id = "Tasks".id
        join "Projects" on "Tasks".project_id = "Projects".id
        where "Projects".id = %s
        group by "Versions".task_id, "Versions".take_name
    """ % proj_id
    sql_result = db.DBSession.execute(sql)
    sql_result_list = sql_result.fetchall()

    new_list = []
    for tpl in sql_result_list:
        for idx in tpl:
            new_list.append(idx)

    versions = Version.query.filter(Version.id.in_(new_list)).all()
```

**Comment by eoyilmaz** [comment]
The **all()** statement should be the last expression (and remove the
pharantheses):

```python
versions = Version.query.filter(Version.id.in_(sql_result_list)).all()
```

**Comment by fredrikaverpil** [comment]
I think perhaps your old email came through (?), since my previous post already has the **all()** statement as the last expression.
