### ISSUE TITLE
"pip install" fails when stalker exists as dependency

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#56]
I've created a wheel, which has stalker as a dependency. When I install this wheel, it always fails like this:

```
$ pip install [REDACTED]/skalman-2.2.21-py2.py3-none-any.whl
Collecting skalman==2.2.21 from [REDACTED]/skalman-2.2.21-py2.py3-none-any.whl
  Downloading [REDACTED]/skalman-2.2.21-py2.py3-none-any.whl (5.0MB)
    100% |████████████████████████████████| 5.0MB 119kB/s
Collecting six==1.10.0 (from skalman==2.2.21)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting PyYAML==3.12 (from skalman==2.2.21)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 1.3MB/s
Collecting alembic==0.8.8 (from skalman==2.2.21)
  Downloading alembic-0.8.8.tar.gz (970kB)
    100% |████████████████████████████████| 972kB 566kB/s
Collecting packaging (from skalman==2.2.21)
  Downloading packaging-16.8-py2.py3-none-any.whl
Collecting Mako==1.0.6 (from skalman==2.2.21)
  Downloading Mako-1.0.6.tar.gz (575kB)
    100% |████████████████████████████████| 583kB 910kB/s
Collecting Jinja2==2.8 (from skalman==2.2.21)
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 2.3MB/s
Collecting pg8000==1.10.6 (from skalman==2.2.21)
  Downloading pg8000-1.10.6-py2.py3-none-any.whl
Collecting Qt.py==1.0.0b3 (from skalman==2.2.21)
  Downloading Qt.py-1.0.0b3-py2.py3-none-any.whl
Collecting SQLAlchemy==1.1.4 (from skalman==2.2.21)
  Downloading SQLAlchemy-1.1.4.tar.gz (5.1MB)
    100% |████████████████████████████████| 5.1MB 116kB/s
Collecting colorlog==2.10.0 (from skalman==2.2.21)
  Downloading colorlog-2.10.0-py2.py3-none-any.whl
Collecting stalker==0.2.18 (from skalman==2.2.21)
  Downloading stalker-0.2.18.zip (803kB)
    100% |████████████████████████████████| 808kB 739kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zu_evvg4/stalker/setup.py", line 5, in <module>
        import stalker
      File "/tmp/pip-build-zu_evvg4/stalker/stalker/__init__.py", line 39, in <module>
        from stalker.models.auth import (Group, Permission, User, LocalSession, Role,
      File "/tmp/pip-build-zu_evvg4/stalker/stalker/models/auth.py", line 27, in <module>
        from sqlalchemy import (Table, Column, Integer, ForeignKey, String, DateTime,
    ModuleNotFoundError: No module named 'sqlalchemy'
```

This is in my wheel's `setup.py`: 

```python
install_requires=[
        'alembic==0.8.8', 'colorlog==2.10.0', 'Jinja2==2.8', 'Mako==1.0.6',
        'MarkupSafe==0.23', 'pg8000==1.10.6', 'pyseq==0.5.0',
        'python-editor==1.0.1', 'PyYAML==3.12', 'Qt.py==1.0.0b3',
        'requests==2.13.0', 'six==1.10.0', 'SQLAlchemy==1.1.4', 'pytz==2016.10',
        'stalker==0.2.18', 'setuptools', 'packaging'
    ],
```

So it seems the import in that `__init__.py` is causing the issue. Perhaps this should be put inside of a `try/except` clause - or have some detection of it being executed by pip?

The workaround is to first `pip install SQLAlchemy` and then install my wheel.

**Comment by eoyilmaz** [comment]
It is because I'm importing ``stalker`` in ``setup.py`` to read the ``__version__`` variable value. But then stalker starts to import all of the other modules, which depends on ``SQLAlchemy`` and which is not installed yet, because PIP doesn't know that it is a dependency yet.

I fixed this months ago in the development version by literally reading the ``__init__.py`` file and extracting variables with a regular expression.
