### ISSUE TITLE
Cockroach db

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#61]
We're looking to use Cockroach db for some projects where reliability, replication and scalability is very important.

For stalker, I am interested in looking into database replication and I was just wondering... do you think stalker would run on [Cockroach db](https://github.com/cockroachdb/cockroach)?

Here's a quick comparison: https://www.cockroachlabs.com/docs/stable/cockroachdb-in-comparison.html

**Comment by jasperges** [comment]
Looking at [this](https://www.cockroachlabs.com/blog/building-application-cockroachdb-sqlalchemy-2/) it shouldn't be too difficult. As Stalker uses SQLAlchemy as it's ORM it _seems_ like the only thing you have to do is:

> … simply `pip install cockroachdb` and configure SQLAlchemy with a URL that begins with `cockroachdb://` instead of `postgresql://`.

So installing `cockroachdb` for your Stalker install, should be all that is needed.

Hope this helps.

**Comment by fredrikaverpil** [comment]
I tried what @jasperges mentioned and ended up with this dead-end:

```
Traceback (most recent call last):
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
psycopg2.InternalError: duplicate constraint name: "TimeUnit"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\Scripts\skalman-script.py", line 11, in <module>
    load_entry_point('skalman', 'console_scripts', 'skalman')()
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\pkg_resources\__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\pkg_resources\__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\pkg_resources\__init__.py", line 2316, in load
    return self.resolve()
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\pkg_resources\__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\fredrik\code\repos\skalman\skalman\uisetup.py", line 110, in <module>
    from skalman.uilib import filemenu
  File "c:\users\fredrik\code\repos\skalman\skalman\uilib\filemenu.py", line 20, in <module>
    from skalman.uilib.managers import projectmgr
  File "c:\users\fredrik\code\repos\skalman\skalman\uilib\managers\projectmgr.py", line 18, in <module>
    from skalman.utils import projstatus
  File "c:\users\fredrik\code\repos\skalman\skalman\utils\projstatus.py", line 4, in <module>
    skalman.initialize()
  File "c:\users\fredrik\code\repos\skalman\skalman\__init__.py", line 31, in initialize
    stalkerdbsetup.setup_db(**kwargs)
  File "c:\users\fredrik\code\repos\skalman\skalman\lib\stalkerscripts\stalkerdbsetup.py", line 105, in setup_db
    db.setup(database_engine_settings)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\stalker\db\__init__.py", line 76, in setup
    Base.metadata.create_all(engine)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\sql\schema.py", line 3848, in create_all
    tables=tables)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\base.py", line 1920, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\base.py", line 1529, in _run_visitor
    **kwargs).traverse_single(element)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\sql\visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\sql\ddl.py", line 733, in visit_metadata
    _is_metadata_operation=True)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\sql\visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\sql\ddl.py", line 767, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\sql\ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\base.py", line 1002, in _execute_ddl
    compiled
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\util\compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "C:\Users\fredrik\skalman\condaenvs\skalman_standalone_py35\lib\site-packages\sqlalchemy\engine\default.py", line 469, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.InternalError) duplicate constraint name: "TimeUnit"
 [SQL: '\nCREATE TABLE "Tasks" (\n\tid INTEGER NOT NULL, \n\tproject_id INTEGER, \n\tis_milestone BOOLEAN, \n\tallocation_strategy VARCHAR(12) NOT NULL, \n\tpersistent_allocation BOOLEAN NOT NULL, \n\tpriority INTEGER, \n\tbid_timing FLOAT, \n\tbid_un
 VARCHAR(3), \n\tschedule_seconds INTEGER, \n\ttotal_logged_seconds INTEGER, \n\treview_number INTEGER, \n\tgood_id INTEGER, \n\tstatus_list_id INTEGER NOT NULL, \n\tstatus_id INTEGER NOT NULL, \n\tcomputed_start TIMESTAMP WITH TIME ZONE, \n\tstart TI
STAMP WITH TIME ZONE, \n\t"end" TIMESTAMP WITH TIME ZONE, \n\tcomputed_end TIMESTAMP WITH TIME ZONE, \n\tduration INTERVAL, \n\tschedule_unit VARCHAR(3), \n\tschedule_constraint INTEGER NOT NULL, \n\tschedule_timing FLOAT, \n\tschedule_model VARCHAR(8
NOT NULL, \n\tparent_id INTEGER, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(id) REFERENCES "Entities" (id), \n\tFOREIGN KEY(project_id) REFERENCES "Projects" (id), \n\tCONSTRAINT "ResourceAllocationStrategy" CHECK (allocation_strategy IN (\'minallocated\',
'maxloaded\', \'minloaded\', \'order\', \'random\')), \n\tCONSTRAINT "TimeUnit" CHECK (bid_unit IN (\'min\', \'h\', \'d\', \'w\', \'m\', \'y\')), \n\tFOREIGN KEY(good_id) REFERENCES "Goods" (id), \n\tFOREIGN KEY(status_list_id) REFERENCES "StatusLists
(id), \n\tFOREIGN KEY(status_id) REFERENCES "Statuses" (id), \n\tCONSTRAINT "TimeUnit" CHECK (schedule_unit IN (\'min\', \'h\', \'d\', \'w\', \'m\', \'y\')), \n\tCONSTRAINT "TaskScheduleModel" CHECK (schedule_model IN (\'effort\', \'length\', \'durati
\')), \n\tFOREIGN KEY(parent_id) REFERENCES "Tasks" (id)\n)\n\n']
```

So at least it doesn't seem like stalker will work with cockroach db right out of the box. Closing...
