### ISSUE TITLE
Help with SQL query

### ISSUE THREAD

**Issue by fredrikaverpil** [eoyilmaz/stalker#62]
Hi @eoyilmaz ,

I have the following query:

```
versions_id_list = [ ... ]
versions = DBSession.query(Version.id, Version.created_with, Version.name,
                            Version.take_name, Version.version_number,
                            Version.created_by_id, Version.updated_by_id,
                            Version.generic_text).filter(
                                Version.id.in_(versions_id_list)).all()
```

But I would also like to the tags for each version tuple returned (or more preferably, a list of tag IDs). I can't just append `Version.tags` in that query, as it's not a simple `Version` attribute.

How would you do recommend I do this without affecting performance too negatively?
I can easily just perform a query for each returned version, but the way I do this currently, it affects performance negatively when dealing with a large set of versions.

**Comment by eoyilmaz** [comment]
I'm not in front of my computer but you should do something like this:

DBSession.query(Version.id, Version.name, --add the other Version
attributes--, Tag.name).join(Version,
Tag).filter(Version.id.in_(versions_list)).group_by(Version.id,
Version.name, --add the other Version attributes--).all()

This should return the tags as a list as a part of every element returned
by the result proxy. I'll check my answer later this evening and correct it
if it is wrong.

Cheers,

Erkan Özgür Yılmaz
VFX Supervisor & Photographer
www.youtube.com/erkanozguryilmaz

**Comment by fredrikaverpil** [comment]
Hi , thanks so much for the quick reply. However, I think something's not right with the code. I'm getting the following error:

```
sqlalchemy.exc.InvalidRequestError: Can't join table/selectable '"SimpleEntities" JOIN "Entities" ON "SimpleEntities".id = "Entities".id JOIN "Links" ON "Entities".id = "Links".id
JOIN "Versions" ON "Links".id = "Versions".id' to itself
```

**Comment by fredrikaverpil** [comment]
Have you come to the conclusion whether there's a workaround for this or not?
I presume the issue is that I cannot join SimpleEntities and Entities?

**Comment by eoyilmaz** [comment]
Hey Fredrik,

Sorry for my very late answer. I totally missed it. So I had time to play with the query and the following does what you have asked for:

```python

from sqlalchemy.dialects.postgresql import array_agg
from stalker.db.session import DBSession
from stalker import Version, Tag

versions = DBSession.query(Version.id, Version.created_with, Version.name, Version.take_name, Version.version_number, Version.created_by_id, Version.updated_by_id, Version.generic_text, array_agg(Tag.name)).join(Version.tags, Tag).filter(Version.id.in_(version_ids)).group_by(Version.id, Version.created_with, Version.name, Version.take_name, Version.version_number, Version.created_by_id, Version.updated_by_id, Version.generic_text).all()
```

The key here is to use the ``array_agg`` function from ``sqlalchemy.dialects.postgresql`` module.

**Comment by fredrikaverpil** [comment]
Wow, thanks! I didn't know about `array_agg`.

Hm. I'm noticing that if `Version.tags == []` then the `Version` is not returned at all in that SQL query. Do you know what could be the cause of that?

For example, I had two IDs in my `version_ids` list, but I only got one result back from the query because one version did have any empty list as its `Version.tags`.

**Comment by eoyilmaz** [comment]
Yeah I forgot that, use "left_join" instead of "join" ;)

Erkan Özgür Yılmaz
VFX Supervisor & Photographer
www.youtube.com/erkanozguryilmaz

**Comment by fredrikaverpil** [comment]
Hm. I wonder if the left join syntax is different for SQLAlchemy:

```python
    Version.generic_text, array_agg(Tag.name)).left_join(
AttributeError: 'Query' object has no attribute 'left_join'
```

**Comment by eoyilmaz** [comment]
Try using ``outer_join``

**Comment by eoyilmaz** [comment]
Sorry it is ``outerjoin``

**Comment by fredrikaverpil** [comment]
I tried `outer_join`:

```
Version.generic_text, array_agg(Tag.name)).outer_join(
AttributeError: 'Query' object has no attribute 'outer_join
```

But I believe it is supposed to be `outerjoin`, but this also gives me an error:

```
    Version.tags, Tag).filter(Version.id.in_(versions_list)).group_by(
  File "\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2107, in outerjoin
    from_joinpoint=from_joinpoint)
  File "<string>", line 2, in _join
  File "\venv\lib\site-packages\sqlalchemy\orm\base.py", line 201, in generate
    fn(self, *args[1:], **kw)
  File "\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2234, in _join
    outerjoin, full, create_aliases, prop)
  File "\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2307, in _join_left_to_right
    self._join_to_left(l_info, left, right, onclause, outerjoin, full)
  File "\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2411, in _join_to_left
    "Tried joining to %s, but got: %s" % (right, ae))
sqlalchemy.exc.InvalidRequestError: Could not find a FROM clause to join from.  Tried joining to <AliasedClass at 0x1a782f0a898; Tag>, but got: Can't determine join between 'Join object on Join object on Join object on Join object on SimpleEntities(1818929898216) and Entities(1818929901296)(1818930094768) and Links(1818931891392)(1818931891896) and Versions(1818954986608)(1818954988960) and FromGrouping object(1818967975136)' and 'FromGrouping object'; tables have more than one foreign key constraint relationship between them. Please specify the 'onclause' of this join explicitly.
```

**Comment by eoyilmaz** [comment]
Ok it seems like I'm a little bit rusty on my SQLAlchemy skills. Even it was something that I was regularly doing, I couldn't manage to make it work.

While I'm tackling with this, as a workaround you can use pure SQL like this:

```python

import pprint
from stalker.db.session import DBSession

version_ids = []  # int list of version ids

sql = """
select
    "Versions".id,
    "Versions".created_with,
    "Version_SimpleEntities".name,
    "Versions".take_name,
    "Versions".version_number,
    "Version_SimpleEntities".created_by_id,
    "Version_SimpleEntities".updated_by_id,
    "Version_SimpleEntities".generic_text,
    array_agg("Tag_SimpleEntities".name)
from "Versions"
  join "SimpleEntities" as "Version_SimpleEntities" on "Versions".id = "Version_SimpleEntities".id 
  left outer join "Entity_Tags" on "Versions".id = "Entity_Tags".entity_id
  left outer join "SimpleEntities" as "Tag_SimpleEntities" on "Entity_Tags".tag_id = "Tag_SimpleEntities".id
  where "Versions".id in ( {ids} )
  group by
    "Versions".id,
    "Versions".created_with,
    "Version_SimpleEntities".name,
    "Versions".take_name,
    "Versions".version_number,
    "Version_SimpleEntities".created_by_id,
    "Version_SimpleEntities".updated_by_id,
    "Version_SimpleEntities".generic_text
"""

formatted_sql = sql.format(ids=','.join(map(str, version_ids)))

result = DBSession.connection().execute(formatted_sql).fetchall()

pprint.pprint(result)
```

Will output something like:
```
[(2286, u'Maya2017', u'Version_33b7d135-ea52-47e5-9b5b-4099c129315d', u'Main', 1, 31, 31, u'', [u'Tag1', u'Tag2']),
 (2300, u'Maya2017', u'Version_80c4a469-8ef8-45b7-a993-e3e7e7794a6e', u'Main', 2, 31, 31, u'', [None]),
 (2301, u'Maya2017', u'Version_d7608af4-0a39-453b-bb67-ae6f5f0aa523', u'Main', 3, 31, 31, u'', [None]),
 (2302, u'Maya2017', u'Version_9e5d6d3f-28f2-49e0-87ff-686736716867', u'Main', 4, 31, 31, u'', [None]),
 (2303, u'Maya2017', u'Version_51c2bad5-7906-41e8-973b-7fcf0270b7f2', u'Main', 5, 31, 31, u'', [None]),
 (2304, u'Maya2017', u'Version_1537f1ba-5f03-4cbe-8b44-98c828d10c3f', u'Main', 6, 31, 31, u'', [None]),
 (2305, u'Maya2017', u'Version_f9ecec24-2bcf-4cdf-aa96-ce0309cdef90', u'Main', 7, 31, 31, u'', [None]),
 (2306, u'Maya2017', u'Version_2a41e17a-8a22-4b48-899c-ef8add31593c', u'Main', 8, 31, 31, u'', [None]),
 (2317, u'Maya2017', u'Version_d01d4fee-bb6b-48d1-84cc-0658f058ec55', u'Main', 9, 31, 31, u'', [u'Tag2', u'Tag3']),
 (2318, u'Maya2017', u'Version_bd450fc7-7c24-4902-ba4e-8b5eb4e3185b', u'Main', 10, 31, 31, u'', [u'Tag3', u'Tag1']),
 (2319, u'Maya2017', u'Version_40ed6b75-90c3-49bf-8801-16e1aefb326e', u'Main', 11, 31, 31, u'', [None]),
 (2349, u'Maya2017', u'Version_fdc6be01-0f70-43ea-80c8-53a73ad2bac1', u'Main', 12, 31, 31, u'', [None])]
```

I believe this is what you were looking for.

**Comment by eoyilmaz** [comment]
Ok I got it :)

```python
import pprint
from sqlalchemy.dialects.postgresql import array_agg
from stalker.db.session import DBSession
from stalker.models.entity import Entity_Tags
from stalker import Tag, Version

result = DBSession\
    .query(
        Version.id,
        Version.created_with,
        Version.name,
        Version.take_name,
        Version.version_number,
        Version.created_by_id,
        Version.updated_by_id,
        Version.generic_text,
        array_agg(Tag.name)
    )\
    .outerjoin(Entity_Tags, Version.id == Entity_Tags.c.entity_id) \
    .outerjoin(Tag, Entity_Tags.c.tag_id == Tag.id) \
    .filter(Version.id.in_(version_ids))\
    .group_by(
        Version.id,
        Version.created_with,
        Version.name,
        Version.take_name,
        Version.version_number,
        Version.created_by_id,
        Version.updated_by_id,
        Version.generic_text)\
    .all()

pprint.pprint(result)
```

will print the same result:

```python
[(2286, u'Maya2017', u'Version_33b7d135-ea52-47e5-9b5b-4099c129315d', u'Main', 1, 31, 31, u'', [u'Tag1', u'Tag2']),
 (2300, u'Maya2017', u'Version_80c4a469-8ef8-45b7-a993-e3e7e7794a6e', u'Main', 2, 31, 31, u'', [None]),
 (2301, u'Maya2017', u'Version_d7608af4-0a39-453b-bb67-ae6f5f0aa523', u'Main', 3, 31, 31, u'', [None]),
 (2302, u'Maya2017', u'Version_9e5d6d3f-28f2-49e0-87ff-686736716867', u'Main', 4, 31, 31, u'', [None]),
 (2303, u'Maya2017', u'Version_51c2bad5-7906-41e8-973b-7fcf0270b7f2', u'Main', 5, 31, 31, u'', [None]),
 (2304, u'Maya2017', u'Version_1537f1ba-5f03-4cbe-8b44-98c828d10c3f', u'Main', 6, 31, 31, u'', [None]),
 (2305, u'Maya2017', u'Version_f9ecec24-2bcf-4cdf-aa96-ce0309cdef90', u'Main', 7, 31, 31, u'', [None]),
 (2306, u'Maya2017', u'Version_2a41e17a-8a22-4b48-899c-ef8add31593c', u'Main', 8, 31, 31, u'', [None]),
 (2317, u'Maya2017', u'Version_d01d4fee-bb6b-48d1-84cc-0658f058ec55', u'Main', 9, 31, 31, u'', [u'Tag3', u'Tag2']),
 (2318, u'Maya2017', u'Version_bd450fc7-7c24-4902-ba4e-8b5eb4e3185b', u'Main', 10, 31, 31, u'', [u'Tag3', u'Tag1']),
 (2319, u'Maya2017', u'Version_40ed6b75-90c3-49bf-8801-16e1aefb326e', u'Main', 11, 31, 31, u'', [None]),
 (2349, u'Maya2017', u'Version_fdc6be01-0f70-43ea-80c8-53a73ad2bac1', u'Main', 12, 31, 31, u'', [None])]```

**Comment by fredrikaverpil** [comment]
Fantastic, thank you so much!

**Comment by fredrikaverpil** [comment]
Hi again,

Something got changed with SQLAlchemy 1.3.0 and your [suggested code](https://github.com/eoyilmaz/stalker/issues/62#issuecomment-396700853) stopped working. This is with SQLAlchemy 1.3.4:

```
Traceback (most recent call last):
...
  File "...\stalkerquery.py", line 327, in latest_versions_in_task_fast
    .outerjoin(Entity_Tags, Version.id == Entity_Tags.c.entity_id) \
  File "...\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2263, in outerjoin
    from_joinpoint=from_joinpoint,
  File "<string>", line 2, in _join
  File "...\venv\lib\site-packages\sqlalchemy\orm\base.py", line 220, in generate
    fn(self, *args[1:], **kw)
  File "...\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2418, in _join
    left, right, onclause, prop, create_aliases, outerjoin, full
  File "...\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2441, in _join_left_to_right
    ) = self._join_determine_implicit_left_side(left, right, onclause)
  File "...\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2572, in _join_determine_implicit_left_side  
    "Can't determine which FROM clause to join "
sqlalchemy.exc.InvalidRequestError: Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity. Try adding an explicit ON clause to help resolve the ambiguity.
```

I am unfortunately too inexperienced with SQL to properly understand how to e.g. add such an explicit ON clause. Do you have any suggestions?

**Comment by eoyilmaz** [comment]
Strange, the ON clauses are there already.

I have not upgraded to 1.3.4 yet and now that you reported that some of your queries not working, I don't want to get the risk while in the middle of my project.

So I can not test a possible solution easily.

But, you may continue using the [raw SQL query](https://github.com/eoyilmaz/stalker/issues/62#issuecomment-396684958) which should work without any problem.

**Comment by fredrikaverpil** [comment]
Oh, great. Your raw SQL query still works just fine. I will use this and upgrade to SQLAlchemy 1.3.4 (currently the latest version) in my dev environment. I'll let you know if I encounter any other (breaking) changes.
