### ISSUE TITLE
stalker_pyramid 0.1.0.b1 install error

### ISSUE THREAD

**Issue by plboily** [eoyilmaz/stalker#64]
Hi,
if im doing this with latest python 3.6:
pip install stalker_pyramid
I am having this error:

> Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-u1ko3rm4/stalker-pyramid/setup.py", line 4, in <module>
>         import stalker_pyramid
>       File "/tmp/pip-install-u1ko3rm4/stalker-pyramid/stalker_pyramid/__init__.py", line 30, in <module>
>         from stalker.config import defaults
>     ImportError: cannot import name 'defaults

Any ideas?

Thanks a lot.

**Comment by plboily** [comment]
T fix this, i had to replace in your __init__ 
from stalker.config import defaults
to 
from stalker import defaults
